### ISSUE TITLE
Undefined property: OrisIntel\OnlineMigrator\OnlineMigrator::$notes  

### ISSUE THREAD

**Issue by imTigger** [orisintel/laravel-online-migrator#15]
Environment:
PHP 7.2.19
Laravel 5.8.26

Steps to Reproduce:
Install project
Enable .env ONLINE_MIGRATOR=1

Expected behavior:
Migration should works fine

Current behavior:
In OnlineMigrator.php line 93:
Undefined property: OrisIntel\OnlineMigrator\OnlineMigrator::$notes
                                                                      
I have checked Illuminate\Database\Migrations\Migrator do not have $notes property in 5.8

**Comment by paulrrogers** [comment]
Fixed in #17
